---
- hosts: all
  tasks:
    - name: Installs apache web server
      ansible.builtin.apt:
        pkg: apache2
        state: latest
        update_cache: true

    - name: Push default virtual host configuration
      ansible.builtin.copy:
        src: ../files/awesome-app.conf
        dest: /etc/apache2/sites-available/awesome-app.conf
        mode: 0640
    
    - name: Check that our config is valid
      ansible.builtin.command: apache2ctl configtest

    - name: Activates our virtualhost
      file:
        src: /etc/apache2/sites-available/awesome-app.conf
        dest: /etc/apache2/sites-enabled/awesome-app.conf
        state: link

    # - name: Start Apache
    #   ansible.builtin.command: "service apache2 start" 

    
    - name: Disable the default virtualhost
      file:
        dest: /etc/apache2/sites-enabled/000-default.conf
        state: absent

    - name: Disable the default ssl virtualhost
      file:
        dest: /etc/apache2/sites-enabled/default-ssl.conf
        state: absent

    - name: Ensure destination directory exists
      ansible.builtin.file:
        path: /var/www/awesome-app
        state: directory

    - name: Push html file
      copy:
        src: ../files/index.html
        dest: /var/www/awesome-app/index.html
        mode: preserve

    - name: Start Apache
      ansible.builtin.command: "service apache2 restart" 
